// <auto-generated />
using System;
using ISPHackerEarth.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ISPHackerEarth.Infrastructure.Migrations
{
    [DbContext(typeof(ISPDbContext))]
    [Migration("20240520142227_Add Base Entity")]
    partial class AddBaseEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("ISPHackerEarth.Domain.Entities.ISP", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Contact_No")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("Lowest_Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Max_Speed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ISPs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("695681f5-5a26-4bdf-9b62-dc506e54610a"),
                            Contact_No = "1234567890",
                            CreatedAt = new DateTime(2024, 5, 20, 14, 22, 27, 85, DateTimeKind.Utc).AddTicks(2101),
                            Description = "Bharat Sanchar Nigam Limited | Explore our latest offers and hot tariffs of various services and get activated instantly online. BSNL offers Telecom Training for Students and Professionals. BSNL offers Spaces/Land available for Rent/sale. Mobile Explore various Promotional Offers for Mobile.",
                            Email = "info@bsnl.com",
                            Image = "https://www.bsnl.co.in/Logo-New.png",
                            LastUpdated = new DateTime(2024, 5, 20, 14, 22, 27, 85, DateTimeKind.Utc).AddTicks(2102),
                            Lowest_Price = 399,
                            Max_Speed = "30 Mbps",
                            Name = "BSNL",
                            Rating = 4.0,
                            Status = 0,
                            Url = "https://www.bsnl.co.in/"
                        },
                        new
                        {
                            Id = new Guid("74de6f6e-2822-48b9-86de-7d55343ffe43"),
                            Contact_No = "2134789045",
                            CreatedAt = new DateTime(2024, 5, 20, 14, 22, 27, 85, DateTimeKind.Utc).AddTicks(2119),
                            Description = "Bharti Airtel Limited, commonly known as Airtel, is an Indian multinational telecommunications services company based in New Delhi. It operates in 18 countries across South Asia and Africa, as well as the Channel Islands. Currently, Airtel provides 5G, 4G and LTE Advanced services throughout India. Currently offered services include fixed-line broadband, and voice services depending upon the country of operation.",
                            Email = "info@airtel.com",
                            Image = "https://assets.airtel.in/static-assets/new-home/img/airtel-red.svg",
                            LastUpdated = new DateTime(2024, 5, 20, 14, 22, 27, 85, DateTimeKind.Utc).AddTicks(2119),
                            Lowest_Price = 499,
                            Max_Speed = "Upto 40 Mbps",
                            Name = "Airtel",
                            Rating = 4.4000000000000004,
                            Status = 0,
                            Url = "https://www.airtel.in/"
                        },
                        new
                        {
                            Id = new Guid("60e4085d-5204-44c1-8cd0-9fcfd0b3ba80"),
                            Contact_No = "6789012345",
                            CreatedAt = new DateTime(2024, 5, 20, 14, 22, 27, 85, DateTimeKind.Utc).AddTicks(2121),
                            Description = "Jio is an Indian telecommunications company and a subsidiary of Jio Platforms, headquartered in Navi Mumbai, Maharashtra. It operates a national LTE network with coverage across all 22 telecom circles. Jio offers 5G, 4G and 4G+ services all over India and 5G service almost All Over India. Its 6G service is in the works. Jio soft launched on 27 December 2015 with a beta for partners and employees, and became publicly available on 5 September 2016.",
                            Email = "info@airtel.com",
                            Image = "https://jep-asset.akamaized.net/cms/assets/jiofiber/discover/excited-to-experience-jiofiber.png",
                            LastUpdated = new DateTime(2024, 5, 20, 14, 22, 27, 85, DateTimeKind.Utc).AddTicks(2122),
                            Lowest_Price = 599,
                            Max_Speed = "Upto 30 Mbps",
                            Name = "Jio",
                            Rating = 4.2000000000000002,
                            Status = 0,
                            Url = "https://www.jio.com/fiber"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
